language: node_js
node_js:
  - 10
install:
  - npm install -g codecov
script:
  - npm install
  - npm test -- --coverage
  - if [[ $TRAVIS_EVENT_TYPE != 'pull_request' ||  $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then npm run chromatic; fi
  - codecov
