name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run chromatic
      env:
        CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    - run: npm test --coverage
    - run: npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
